experiment_name: 2023-12-20-et-corrfm-vs-value

ranges_baran:
  dataset:
    - beers
    - flights
    - hospital
    - rayyan
  feature_generators:
    - - auto_instance
      - fd
      - llm_correction
      - llm_master
    - - llm_correction
    - - auto_instance
      - fd
      - value
      - llm_master
    - - value

config_baran:
  dataset: "1481"
  n_rows: null
  error_fraction: 1
  error_class: "simple_mcar"
  labeling_budget: 20
  synth_tuples: 100
  auto_instance_cache_model: false
  clean_with_user_input: true
  gpdep_threshold: 0.3
  training_time_limit: 90
  feature_generators:
    - fd
  classification_model: "ABC"
  vicinity_orders:
    - 1
  vicinity_feature_generator: "naive"
  n_best_pdeps: 3
  synth_cleaning_threshold: 0.9
  test_synth_data_direction: "user_data"
  pdep_features:
    - pr
  fd_feature: "norm_gpdep"
  domain_model_threshold: 0.01


ranges_renuver:
  dataset:
    - bridges
    - cars
    - glass
    - restaurant
  error_fraction:
    - 1
    - 3
  feature_generators:
    - - auto_instance
      - fd
      - llm_correction
      - llm_master
    - - llm_correction
    - - auto_instance
      - fd
      - value
      - llm_master
    - - value

config_renuver:
  dataset: "1481"
  n_rows: null
  error_fraction: 1
  error_class: "simple_mcar"
  labeling_budget: 20
  synth_tuples: 100
  auto_instance_cache_model: false
  clean_with_user_input: true
  gpdep_threshold: 0.3
  training_time_limit: 90
  feature_generators:
    - fd
  classification_model: "ABC"
  vicinity_orders:
    - 1
  vicinity_feature_generator: "naive"
  n_best_pdeps: 3
  synth_cleaning_threshold: 0.9
  test_synth_data_direction: "user_data"
  pdep_features:
    - pr
  fd_feature: "norm_gpdep"
  domain_model_threshold: 0.01

ranges_openml:
  dataset:
    - "6"
    - "137"
    - "151"
    - "184"
    - "1481"
    - "41027"
    - "43572"
  error_fraction:
    - 1
    - 5
  error_class:
    - "simple_mcar"
    - "imputer_simple_mcar"
  feature_generators:
    - - auto_instance
      - fd
      - llm_correction
      - llm_master
    - - llm_correction
    - - auto_instance
      - fd
      - value
      - llm_master
    - - value

config_openml:
  dataset: "1481"
  n_rows: 1000
  error_fraction: 1
  error_class: "simple_mcar"
  labeling_budget: 20
  synth_tuples: 100
  auto_instance_cache_model: false
  clean_with_user_input: true
  gpdep_threshold: 0.3
  training_time_limit: 90
  feature_generators:
    - fd
  classification_model: "ABC"
  vicinity_orders:
    - 1
  vicinity_feature_generator: "naive"
  n_best_pdeps: 3
  synth_cleaning_threshold: 0.9
  test_synth_data_direction: "user_data"
  pdep_features:
    - pr
  fd_feature: "norm_gpdep"
  domain_model_threshold: 0.01

runs: 3
