apiVersion: v1
kind: Pod
metadata:
  name: pvc-access-pod
spec:
  containers:
  - args:
    - while true; do sleep 30; done;
    command:
    - /bin/bash
    - -c
    - --
    image: debian
    name: pvc-access-pod
    volumeMounts:
    - mountPath: /data
      name: data-volume
  volumes:
  - name: data-volume
    persistentVolumeClaim:
      claimName: garf-results
