apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: garf-results
  namespace: pjung
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: shared
