apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mirmir-results-volume
  namespace: pjung
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: shared
